# Generated by Django 4.2.7 on 2025-11-27 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_proof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardanoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=64, unique=True)),
                ('from_address', models.CharField(max_length=120)),
                ('to_address', models.CharField(max_length=120)),
                ('amount_ada', models.DecimalField(decimal_places=6, max_digits=20)),
                ('amount_lovelace', models.BigIntegerField()),
                ('fee_lovelace', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('submitted', 'Soumise'), ('confirmed', 'Confirmée'), ('failed', 'Échouée')], default='submitted', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api_proof.cardanowallet')),
            ],
        ),
    ]
