# Generated by Django 4.2.7 on 2025-11-27 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_proof', '0002_cardanotransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardanowallet',
            name='is_read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardanowallet',
            name='stake_address',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cardanowallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
    ]
