# Generated by Django 4.2.7 on 2025-12-06 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_proof', '0003_cardanowallet_is_read_only_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardanoNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(db_index=True, max_length=255)),
                ('asset_name', models.CharField(db_index=True, max_length=255)),
                ('fingerprint', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('nft_type', models.CharField(choices=[('certification', 'Certification'), ('art', 'Art'), ('collectible', 'Collectible'), ('utility', 'Utility'), ('other', 'Autre')], default='certification', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('minted', 'Minté'), ('received', 'Reçu'), ('sent', 'Envoyé'), ('burned', 'Brûlé')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='api_proof.cardanowallet')),
            ],
            options={
                'db_table': 'cardano_nfts',
                'ordering': ['-created_at'],
                'unique_together': {('policy_id', 'asset_name')},
            },
        ),
        migrations.CreateModel(
            name='NFTPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('policy_id', models.CharField(max_length=255, unique=True)),
                ('policy_script', models.TextField()),
                ('policy_type', models.CharField(choices=[('single_issuer', 'Émetteur unique'), ('multi_issuer', 'Multi-émetteurs'), ('time_locked', 'Verrouillé temporel')], default='single_issuer', max_length=20)),
                ('valid_before', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nft_policies',
            },
        ),
        migrations.CreateModel(
            name='CertificationNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_type', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('verification_url', models.URLField(blank=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revocation_reason', models.TextField(blank=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certifications', to=settings.AUTH_USER_MODEL)),
                ('nft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='api_proof.cardanonft')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certification_nfts',
            },
        ),
    ]
